In [1]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9])
#vektör 9x1
print(array.shape)

(9,)


In [2]:
a=array.reshape(3,3)

In [3]:
print(a.shape)

(3, 3)


In [5]:
print("Boyutu: ", a.ndim)
print("Size: ",a.size)

Boyutu:  2
Size:  9


In [6]:
type(a)

numpy.ndarray

In [10]:
array2=np.array([ [1,2,3,4] , [5,6,7,8] ])
array3=np.zeros( (3,4) )
array4=np.ones( (5,5) )

array5=np.arange(10,50,5)

In [8]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
array3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
array4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
array5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
array6=np.linspace(1,50,150)# beliritlen ralıklarda 150 sayı üretti

In [15]:
array6

array([ 1.        ,  1.32885906,  1.65771812,  1.98657718,  2.31543624,
        2.6442953 ,  2.97315436,  3.30201342,  3.63087248,  3.95973154,
        4.2885906 ,  4.61744966,  4.94630872,  5.27516779,  5.60402685,
        5.93288591,  6.26174497,  6.59060403,  6.91946309,  7.24832215,
        7.57718121,  7.90604027,  8.23489933,  8.56375839,  8.89261745,
        9.22147651,  9.55033557,  9.87919463, 10.20805369, 10.53691275,
       10.86577181, 11.19463087, 11.52348993, 11.85234899, 12.18120805,
       12.51006711, 12.83892617, 13.16778523, 13.4966443 , 13.82550336,
       14.15436242, 14.48322148, 14.81208054, 15.1409396 , 15.46979866,
       15.79865772, 16.12751678, 16.45637584, 16.7852349 , 17.11409396,
       17.44295302, 17.77181208, 18.10067114, 18.4295302 , 18.75838926,
       19.08724832, 19.41610738, 19.74496644, 20.0738255 , 20.40268456,
       20.73154362, 21.06040268, 21.38926174, 21.71812081, 22.04697987,
       22.37583893, 22.70469799, 23.03355705, 23.36241611, 23.69

In [17]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1+v2)

[5 7 9]


In [18]:
print(v1*v2)

[ 4 10 18]


In [20]:
c=np.array([ [1,2,3],[4,5,6] ])
d=np.array([ [7,8,9] ]) 
print(c*d)

[[ 7 16 27]
 [28 40 54]]


In [24]:
e=np.random.random((5,5))

In [25]:
e

array([[0.25705784, 0.26562699, 0.15342736, 0.70572862, 0.11070018],
       [0.54037932, 0.98617223, 0.08281885, 0.31423371, 0.07043679],
       [0.0103468 , 0.10912103, 0.85992492, 0.15338441, 0.62984711],
       [0.00985592, 0.46483366, 0.08481601, 0.96887405, 0.69667749],
       [0.96785906, 0.01012671, 0.78642279, 0.16303978, 0.41691897]])

In [28]:
print(e.max())#e dizisindeki maksimum değeri verir 

0.983164926362227


In [29]:
print(e.min())  #e dizisindeki minumum değeri verir 

0.04375949756611153


In [31]:
print(e.sum()) #e dizisindeki tüm değerlerin toplamınıverir 

14.624381241606324


In [33]:
liste=[1,2,3,4]

In [35]:
type(liste)

list

In [36]:
y_array=np.array(liste) #listeyi array e dönüştürür

In [37]:
y_array

array([1, 2, 3, 4])

In [38]:
liste2=list(y_array) # array i listreye dönüştürür.

In [39]:
liste2

[1, 2, 3, 4]